server:
  port: 3000
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://10.0.38.112:3306/media?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: HNIEACMore
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    default-encoding: utf-8
    host: smtp.exmail.qq.com
    username: tigarette@hnieacm.com
    password: cmRecGzWsGoZ2Jnd